language: java
jdk:
  - openjdk11
branches:
  only:
    - development
    
# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2
    
before_install:
  - chmod +x mvnw    

#notifications:
#  email:
#    recipients:
#      - yongschoi@naver.com
#    on_failure: always

after_script:
  - bash ./telegram_notification.sh