language: java
jdk:
  - openjdk11
branches:
  only:
    - development
    
# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2
    
before_install:
  - chmod +x mvnw    

notifications:
  email:
    recipients:
      - yongschoi@naver.com
    on_success: always

after_success:
  - curl -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage -d chat_id=$TELEGRAM_CHAT_ID -d "text=Build Complete"